let roadmapELements = [
    {
        id: 1,
        title: "Read Articles/Papers and Register",
        location: "Milestone 1 - Planning",
        milestone: "1",
        description: "Research about Augmented reality",
        buttons: [{buttonText: "Assigned to all"}],
        date: "October 15th - October 25th",
        icon: "research",
    },
    {
        id: 2,
        title: "Logos",
        location: "Milestone 1 - Planning",
        milestone: "1",
        description: "Logo design",
        buttons: [{buttonText: "Catarina"}],
        date: "October 28th",
        icon: "development",
    },
    {
        id: 3,
        title: "Website scratch",
        location: "Milestone 2 - Inception",
        milestone: "2",
        description: "Elaboration of a first version of the Website",
        buttons: [{buttonText: "Ricardo"}],
        date: "October 28th - December 12th",
        icon: "development",
    },
    
    {
        id: 4,
        title: "Project Calendar/Workplan",
        location: "Milestone 1 - Planning",
        milestone: "1",
        description: "Building the project's Calendar/Workplan",
        buttons: [
            {buttonText: "Rui"},
            {buttonText: "Catarina"}
        ],
        date: "October 29th - October 10th",
        icon: "development",
    },
    {
        id: 5,
        title: "Project Prentation",
        location: "Milestone 1 - Planning",
        milestone: "1",
        description: "Preparing a presentation of the project",
        buttons: [
            {buttonText: "Rui"},
            {buttonText: "Catarina"},
            {buttonText: "Beatriz"}
        ],
        date: "October 29th - November 11th",
        icon: "research",
    },
    {
        id: 6,
        title: "Communication plan",
        location: "Milestone 1 - Planning",
        milestone: "1",
        description: "Elaboration of a Communication plan",
        buttons: [
            {buttonText: "Catarina"},
            {buttonText: "Beatriz"},
            {buttonText: "Telmo"}
        ],
        date: "",
        icon: "research",
    },
    {
        id: 7,
        title: "Prototype 1 - Pop up",
        location: "Milestone 2 - Inception",
        milestone: "2",
        description: "Pop-up flashcard with peace details",
        buttons: [{buttonText: "Beatriz"}],
        date: "December 6th - December 20th",
        icon: "development",
    },
    {
        id: 8,
        title: "Prototype 1 - QR Code Reader",
        location: "Milestone 2 - Inception",
        milestone: "2",
        description: "QR code reader",
        buttons: [
            {buttonText: "Catarina"},
            {buttonText: "Ricardo"},
            {buttonText: "Telmo"}],
        date: "December 6th - December 20th",
        icon: "development",
    },
    {
        id: 9,
        title: "Prototype 1 - Object Detection App",
        location: "Milestone 2 - Inception",
        milestone: "2",
        description: "Object Detection",
        buttons: [
            {buttonText: "Catarina"},
            {buttonText: "Ricardo"},
            {buttonText: "Telmo"}
        ],
        date: "December 6th - December 20th",
        icon: "development",
    },
    {
        id: 10,
        title: "Tecnical Report",
        location: "Milestone 2 - Inception",
        milestone: "2",
        description: "Elaboration of the tecnical report",
        buttons: [{buttonText: "Assigned to All"}],
        date: "December 6th - December 22nd",
        icon: "research",
    },
    {
        id: 11,
        title: "Google Glasses Software Exploit",
        location: "Milestone 2 - Inception",
        milestone: "2",
        description: "Google Glasses Software Exploit",
        buttons: [
            {buttonText: "Catarina"},
            {buttonText: "Ricardo"},
            {buttonText: "Telmo"}
        ],
        date: "December 8th - December 20th",
        icon: "research",
    },
    {
        id: 12,
        title: "Project Presentation",
        location: "Milestone 2 - Inception",
        milestone: "2",
        description: "Presentation",
        buttons: [
            {buttonText: "Rui"},
            {buttonText: "Catarina"}
        ],
        date: "December 10th - December 20th",
        icon: "research",
    },
    {
        id: 13,
        title: "Augmented Reality projection sample",
        location: "Milestone 2 - Inception",
        milestone: "2",
        description: "Research and Development of a sample that can project a 3D Model of the piece to apply once the QR is scanned",
        buttons: [{buttonText: "Beatriz"}],
        date: "January 12th - February 19th",
        icon: "development",
    },
    {
        id: 14,
        title: "Android Studio",
        location: "Milestone 3 - Elaboration",
        milestone: "3",
        description: "Practice using Androis studio - problem solving",
        buttons: [{buttonText: "Assigned to All"}],
        date: "February 15th - March 12th",
        icon: "development",
    },
    {
        id: 15,
        title: "Color Detetion",
        location: "Milestone 3 - Elaboration",
        milestone: "3",
        description: "Color detetion",
        buttons: [{buttonText: "Telmo"}],
        date: "February 16th - March 5th",
        icon: "development",
    },
    {
        id: 16,
        title: "Coordinates Detection",
        location: "Milestone 3 - Elaboration",
        milestone: "3",
        description: "Coordinates Detection",
        buttons: [{buttonText: "Ricardo"}],
        date: "February 16th - March 5th",
        icon: "development",
    },
    {
        id: 17,
        title: "Scenario Creation",
        location: "Milestone 3 - Elaboration",
        milestone: "3",
        description: "Scenario Creation",
        buttons: [{buttonText: "Catarina"}],
        date: "March 3rd",
        icon: "research",
    },
    {
        id: 18,
        title: "Database Update",
        location: "Milestone 3 - Elaboration",
        milestone: "3",
        description: "Database Update",
        buttons: [
            {buttonText: "Catarina"},
            {buttonText: "Rui"}
        ],
        date: "March 3rd - March 6th",
        icon: "research",
    },
    {
        id: 19,
        title: "Website Update",
        location: "Milestone 3 - Elaboration",
        milestone: "3",
        description: "Update website and create new features",
        buttons: [{buttonText: "Beatriz"}],
        date: "Since March 6th",
        icon: "development",
    },
    {
        id: 20,
        title: "Tecnical Report",
        location: "Milestone 3 - Elaboration",
        milestone: "3",
        description: "Tecnical Report",
        buttons: [{buttonText: "Rui"}],
        date: "Since March 10th",
        icon: "research",
    },
    {
        id: 21,
        title: "Project Presentation",
        location: "Milestone 3 - Elaboration",
        milestone: "3",
        description: "Presentation",
        buttons: [{buttonText: "Rui"}],
        date: "Since March 12th",
        icon: "research",
    },
];
export default roadmapELements;
