let roadmapELements = [
    {
        id: 1,
        title: "Read Articles/Papers and Register",
        location: "Milestone 1 - Planning",
        description: "Research about Augmented reality....",
        buttonText: "Assigned to all",
        date: "October 15th - October 25th",
        icon: "research",
    },
    {
        id: 2,
        title: "Logos",
        location: "Milestone 1 - Planning",
        description: "Logo design",
        buttonText: "Catarina",
        date: "October 28th",
        icon: "development",
    },
    {
        id: 3,
        title: "Website scratch",
        location: "Milestone 2 - Inception",
        description: "Preparing presentation",
        buttonText: "Ricardo",
        date: "October 28th - December 12th",
        icon: "development",
    },
    
    {
        id: 4,
        title: "Project Calendar/Workplan",
        location: "Milestone 1 - Planning",
        description: "Preparing presentation",
        buttonText: "Rui, Catarina",
        date: "October 29th - October 10th",
        icon: "development",
    },
    {
        id: 5,
        title: "Project Prentation",
        location: "Milestone 1 - Planning",
        description: "Research about Augmented reality....",
        buttonText: "Rui, Catarina, Beatriz",
        date: "October 29th - November 11th",
        icon: "research",
    },
    {
        id: 6,
        title: "Communication plan",
        location: "Milestone 1 - Planning",
        description: "Preparing presentation",
        buttonText: "Catarina, Beatriz, Telmo",
        date: "",
        icon: "research",
    },
    {
        id: 7,
        title: "Prototype 1 - Pop up",
        location: "Milestone 2 - Inception",
        description: "Pop-up flashcard with peace details",
        buttonText: "Beatriz",
        date: "December 6th - December 20th",
        icon: "development",
    },
    {
        id: 8,
        title: "Prototype 1 - QR Code Reader",
        location: "Milestone 2 - Inception",
        description: "QR code reader",
        buttonText: "Catarina, Ricardo, Telmo",
        date: "December 6th - December 20th",
        icon: "development",
    },
    {
        id: 9,
        title: "Prototype 1 - Object Detection App",
        location: "Milestone 2 - Inception",
        description: "QR code reader",
        buttonText: "Catarina, Ricardo, Telmo",
        date: "December 6th - December 20th",
        icon: "development",
    },
    {
        id: 10,
        title: "Tecnical Report",
        location: "Milestone 2 - Inception",
        description: "Elaboration of the tecnical report",
        buttonText: "Assigned to All",
        date: "December 6th - December 22nd",
        icon: "research",
    },
    {
        id: 11,
        title: "Google Glasses Software Exploit",
        location: "Milestone 2 - Inception",
        description: "Elaboration of the tecnical report",
        buttonText: "Catarina, Ricardo, Telmo",
        date: "December 8th - December 20th",
        icon: "research",
    },
    {
        id: 12,
        title: "Project Presentation",
        location: "Milestone 2 - Inception",
        description: "Elaboration of the tecnical report",
        buttonText: "Rui, Catarina",
        date: "December 10th - December 20th",
        icon: "research",
    },
    {
        id: 13,
        title: "Augmented Reality projection sample",
        location: "Milestone 2 - Inception",
        description: "Research and Development of a sample that can project a 3D Model of the piece to apply once the QR is scanned",
        buttonText: "Beatriz",
        date: "January 12th - February 19th",
        icon: "development",
    },
    {
        id: 14,
        title: "Android Studio",
        location: "Milestone 3 - Elaboration",
        description: "Android Studio",
        buttonText: "Assigned to All",
        date: "February 15th - March 12th",
        icon: "development",
    },
    {
        id: 15,
        title: "Color Detetion",
        location: "Milestone 3 - Elaboration",
        description: "Color detetion",
        buttonText: "Telmo",
        date: "February 16th - March 5th",
        icon: "development",
    },
    {
        id: 16,
        title: "Coordinates Detection",
        location: "Milestone 3 - Elaboration",
        description: "Coordinates Detection",
        buttonText: "Ricardo",
        date: "February 16th - March 5th",
        icon: "development",
    },
    {
        id: 17,
        title: "Scenario Creation",
        location: "Milestone 3 - Elaboration",
        description: "Scenario Creation",
        buttonText: "Catarina",
        date: "March 3rd",
        icon: "research",
    },
    {
        id: 18,
        title: "Database Update",
        location: "Milestone 3 - Elaboration",
        description: "Database Update",
        buttonText: "Catarina, Rui",
        date: "March 3rd - March 6th",
        icon: "research",
    },
    {
        id: 19,
        title: "Tecnical Report",
        location: "Milestone 3 - Elaboration",
        description: "Tecnical Report",
        buttonText: "Rui",
        date: "Since March 10th",
        icon: "research",
    },
    {
        id: 20,
        title: "Project Presentation",
        location: "Milestone 3 - Elaboration",
        description: "Presentation",
        buttonText: "Rui",
        date: "Since March 12th",
        icon: "research",
    },
];
export default roadmapELements;
